# render.yaml
# -----------------------------------------------------------------------------
# FINAL CORRECTED BLUEPRINT - Version 3
# This version explicitly defines the runtime for each service and uses the
# correct properties for connecting them, resolving all previous errors.
# -----------------------------------------------------------------------------

services:
  # -----------------------------------------------------------------
  # Service 1: The PostgreSQL Database
  # Using the correct 'db' type for a managed database.
  # -----------------------------------------------------------------
  - type: db
    name: skysniper-db
    # 'runtime: postgres' tells Render what kind of database this is.
    runtime: postgres
    plan: free # Change to 'starter' or higher for production use
    # We define the database name and user here.
    databaseName: skysniperdb
    user: skysniper_user

  # -----------------------------------------------------------------
  # Service 2: The Redis Cache & Job Queue
  # (This definition is correct)
  # -----------------------------------------------------------------
  - type: redis
    name: skysniper-cache
    plan: free
    ipAllowList: []

  # -----------------------------------------------------------------
  # Service 3: The SkySniper X NestJS Application
  # -----------------------------------------------------------------
  - type: web
    name: skysniper-app
    plan: free
    # CRITICAL FIX: Explicitly set the runtime to 'docker'.
    runtime: docker
    # This now becomes valid because the runtime is 'docker'.
    dockerfilePath: ./Dockerfile

    healthCheckPath: /

    envVars:
      # --- Automatic Variables (linked from other Render services) ---
      - key: DATABASE_URL
        fromService:
          type: db # Match the service type above
          name: skysniper-db
          # 'connectionString' is a valid property for the 'db' type.
          property: connectionString
      - key: REDIS_URL # 👈 We will use the full URL now.
        fromService:
          type: redis
          name: skysniper-cache
          # 'connectionString' is the correct property for Redis as well.
          property: connectionString

      # --- Manual Secret Variables (you MUST set these in the Render dashboard) ---
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_TOKEN
        sync: false

      # --- Standard Variables ---
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
