# render.yaml (DEFINITIVE, FINAL VERSION USING RENDER'S DATABASE)

databases:
  - name: skysniper-db
    plan: free
    databaseName: skysniperdb
    user: skysniper_user

services:
  - type: redis
    name: skysniper-cache
    plan: free
    ipAllowList: []

  - type: web
    name: skysniper-app
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: skysniper-db
          property: connectionString
      - key: DIRECT_URL
        fromDatabase:
          name: skysniper-db
          property: connectionString # Using the same string for both is correct on Render
      - key: REDIS_URL
        fromService:
          type: redis
          name: skysniper-cache
          property: connectionString
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
