# render.yaml (DEFINITIVE, FINAL VERSION USING RENDER'S DATABASE)

# We declare our managed database in its own top-level block.
databases:
  - name: skysniper-db
    plan: free
    databaseName: skysniperdb
    user: skysniper_user

services:
  # Redis service remains the same
  - type: redis
    name: skysniper-cache
    plan: free
    ipAllowList: []

  # Web service remains the same
  - type: web
    name: skysniper-app
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      # --- Automatic Variables (linked from Render's own resources) ---
      - key: DATABASE_URL
        fromDatabase:
          name: skysniper-db
          property: connectionString
      - key: DIRECT_URL # We still provide both URLs for Prisma
        fromDatabase:
          name: skysniper-db
          property: internalConnectionString # Use internal for migrations
      - key: REDIS_URL
        fromService:
          type: redis
          name: skysniper-cache
          property: connectionString

      # --- Manual Secret Variables ---
      - key: AIzaSyC6ZjLR3mtq4odTY9q2AhqNG2v7uzvh9r0
        sync: false
      - key: 9907113529
        sync: false

      # --- Standard Variables ---
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
