# render.yaml
# -----------------------------------------------------------------------------
# FINAL, DEFINITIVE BLUEPRINT - Version 5
# This version correctly separates Databases from Services, which is the
# proper way to define infrastructure in a Render blueprint.
# -----------------------------------------------------------------------------

# We declare our managed databases in their own top-level block.
databases:
  - name: skysniper-db
    plan: free # Change to 'starter' or higher for production use
    # We specify the initial database name and user to be created.
    databaseName: skysniperdb
    user: skysniper_user

# We declare our running services (web apps, workers, redis) in this block.
services:
  # -----------------------------------------------------------------
  # Service 1: The Redis Cache & Job Queue
  # -----------------------------------------------------------------
  - type: redis
    name: skysniper-cache
    plan: free
    ipAllowList: [] # Allows connections from other services in our account.

  # -----------------------------------------------------------------
  # Service 2: The SkySniper X NestJS Application
  # -----------------------------------------------------------------
  - type: web
    name: skysniper-app
    plan: free
    # We explicitly tell Render this is a Docker-based service.
    runtime: docker
    dockerfilePath: ./Dockerfile

    healthCheckPath: /

    envVars:
      # --- Automatic Variables (linked from other resources) ---
      - key: DATABASE_URL
        # We use 'fromDatabase' to link to our managed database.
        fromDatabase:
          name: skysniper-db
          property: connectionString
      - key: REDIS_URL
        # We use 'fromService' to link to our Redis service.
        fromService:
          type: redis
          name: skysniper-cache
          property: connectionString

      # --- Manual Secret Variables (you MUST set these in the Render dashboard) ---
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_TOKEN
        sync: false

      # --- Standard Variables ---
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
