# render.yaml (DEFINITIVE, FINAL VERSION - CORRECT PROPERTY)

# We declare our managed database in its own top-level block.
databases:
  - name: skysniper-db
    plan: free
    databaseName: skysniperdb
    user: skysniper_user

services:
  # Redis service remains the same
  - type: redis
    name: skysniper-cache
    plan: free
    ipAllowList: []

  # Web service remains the same
  - type: web
    name: skysniper-app
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      # --- Automatic Variables (linked from Render's own resources) ---
      - key: DATABASE_URL
        fromDatabase:
          name: skysniper-db
          property: connectionString # This is the correct property for the runtime URL
      - key: DIRECT_URL
        fromDatabase:
          name: skysniper-db
          property: connectionString # DEFINITIVE FIX: Use the same correct property for the direct/migration URL
      - key: REDIS_URL
        fromService:
          type: redis
          name: skysniper-cache
          property: connectionString

      # --- Manual Secret Variables ---
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_TOKEN
        sync: false

      # --- Standard Variables ---
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
