# render.yaml
# -----------------------------------------------------------------------------
# FINAL BLUEPRINT - Version 6
# This version is configured to use an EXTERNAL Supabase database and
# correctly handles all environment variables as secrets.
# -----------------------------------------------------------------------------

services:
  # -----------------------------------------------------------------
  # Service 1: The Redis Cache & Job Queue (Managed by Render)
  # -----------------------------------------------------------------
  - type: redis
    name: skysniper-cache
    plan: free
    ipAllowList: [] # Allows connections from other services in our account.

  # -----------------------------------------------------------------
  # Service 2: The SkySniper X NestJS Application (Hosted by Render)
  # -----------------------------------------------------------------
  - type: web
    name: skysniper-app
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile

    healthCheckPath: /

    envVars:
      # --- Automatic Variable from Render Redis ---
      - key: REDIS_URL
        fromService:
          type: redis
          name: skysniper-cache
          property: connectionString

      # --- Configuration Variable ---
      - key: GEMINI_MODEL_URL
        value: "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent"

      # --- Manual Secret Variables (you MUST set these in the Render dashboard) ---
      # 'sync: false' is critical. It tells Render you will provide these securely.
      - key: DATABASE_URL # Your Supabase Postgres connection string
        sync: false
      - key: GEMINI_API_KEY # Your NEW Gemini API key
        sync: false
      - key: ADMIN_TOKEN # Your NEW, strong admin token
        sync: false

      # --- Standard Variables ---
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
