# render.yaml
# -----------------------------------------------------------------------------
# CORRECTED BLUEPRINT for deploying the SkySniper X backend on Render.
# This version uses the updated syntax for PostgreSQL services.
# -----------------------------------------------------------------------------

services:
  # -----------------------------------------------------------------
  # Service 1: The PostgreSQL Database
  # This is the updated, simplified, and correct way to define the database.
  # -----------------------------------------------------------------
  - type: pserv
    name: skysniper-db
    plan: free # Change to 'starter' or higher for production use
    # NOTE: 'databaseName' and 'postgres' block are no longer needed here.
    # Render will automatically create a default database for you.

  # -----------------------------------------------------------------
  # Service 2: The Redis Cache & Job Queue
  # (This section was already correct)
  # -----------------------------------------------------------------
  - type: redis
    name: skysniper-cache
    plan: free # Change to a paid plan for production use
    ipAllowList: [] # This is valid for Redis and allows other Render services to connect.

  # -----------------------------------------------------------------
  # Service 3: The SkySniper X NestJS Application
  # -----------------------------------------------------------------
  - type: web
    name: skysniper-app
    plan: free # Change to 'starter' or higher for production use
    dockerfilePath: ./Dockerfile

    healthCheckPath: /

    envVars:
      # --- Automatic Variables (linked from other Render services) ---
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: skysniper-db
          property: connectionString # This correctly pulls the full URL from the service above.
      - key: REDIS_HOST
        fromService:
          type: redis
          name: skysniper-cache
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: skysniper-cache
          property: port
      - key: REDIS_PASSWORD
        fromService:
          type: redis
          name: skysniper-cache
          property: password

      # --- Manual Secret Variables (you MUST set these in the Render dashboard) ---
      - key: GEMINI_API_KEY
        sync: false
      - key: ADMIN_TOKEN
        sync: false

      # --- Standard Variables ---
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
